# Generated by Django 3.0.8 on 2020-07-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
    ]
