# Generated by Django 3.0.8 on 2020-07-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200724_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModelo',
            new_name='TestModelos',
        ),
    ]
