# Generated by Django 3.0.8 on 2020-07-24 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200724_2306'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestModelos',
            new_name='Prueba',
        ),
    ]
