# Generated by Django 3.0.8 on 2020-08-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0005_auto_20200806_1555'),
        ('persona', '0007_empleado_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('first_name', 'last_name', 'departamento')},
        ),
    ]
